#ifndef PARAMETERS_H_
#define PARAMETERS_H_

#include <vector>

//note: if you do any change in the order of field names in enum, then make sure that same change is done in csvHeader and vice-versa

const int totalFields = 48;

enum {
STATION_CODE,
STATION_PLACE_NAME,
STATION_LONGITUDE,
STATION_LATITUDE,
DAY,
MONTH,
YEAR,
READING_NO,
NEAREST_HOUR,
WIND_INDICATOR,
PRECIPITATION_INDICATOR,
STATION_TYPE,
CLOUD_BASE_OF_LOWEST_CLOUD_SEEN_M,
CLOUD_COVER,
WIND_DIRECTION,
SURFACE_WIND_SPEED,
OPTIONAL_WIND_SPEED,
TEMPERATURE_C,
DEWPOINT_C,
RELATIVE_HUMIDITY_PERC,
STATION_PRESSURE_HPA,
SEA_LEVEL_PRESSURE_MB,
PRESSURE_CHANGE_IN_LAST_3HRS_HPA,
PRESSURE_TENDENCY,
LIQUID_PRECIPITATION_AMOUNT_SEC_1_MM,
LIQUID_PRECIPITATION_DURATION_SEC_1_HRS,
PRESENT_WEATHER,
PAST_WEATHER_MOST_SIGNIFICANT,
PAST_WEATHER_SECOND_MOST_SIGNIFICANT,
AMOUNT_OF_LOWERLOW_MIDDLE_CLOUD_COVER,
LOW_CLOUD_TYPE,
MIDDLE_CLOUD_TYPE,
HIGH_CLOUD_TYPE,
TIME_OF_OBERSERVATION_HHMM,
MAX_TEMP_C,
MIN_TEMP_LAST_24HR_C,
STATE_OF_THE_GROUND_WITHOUT_SNOW_OR_MEASURABLE_ICE_COVER,
SNOW_DEPTH_CM,
STATE_OF_GROUND,
ADDITIONAL_INFORMATION,
LIQUID_PRECIPITATION_AMOUNT_SEC_2MM,
PRECIPITATION_DURATION_SEC_2_HR,
_24_HR_PRECIPITATION_MM,
CLOUD_COVERAGE_OF_LAYER,
GENUS_OF_CLOUD,
HEIGHT_OF_CLOUD_BASE,
SPECIAL_PHENOMENA_GROUP,
VISIBILITY_KM
};

const std::vector<std::string> csvHeader{
"station code",
"station place name",
"station latitude",
"station longitude",
"day",
"month",
"year",
"reading no",
"nearest hour",
"wind indicator",
"precipitation indicator",
"station type",
"cloud base of lowest cloud seen (m)",
"cloud cover",
"wind direction",
"surface wind speed",
"optional wind speed",
"temperature (C)",
"dewpoint (C)",
"relative humidity (%)",
"station pressure (hPa)",
"sea level pressure (mb)",
"pressure change in last 3hrs (hPa)",
"pressure tendency",
"liquid precipitation amount Sec 1 (mm)",
"liquid precipitation duration Sec 1 (hrs)",
"present weather",
"past weather (most significant)",
"past weather (second most significant)",
"amount of lower(low/middle) cloud cover",
"low cloud type",
"middle cloud type",
"high cloud type",
"time of oberservation (hh:mm)",
"max temp (C)",
"min temp last 24hr (C)",
"State of the ground without snow or measurable ice cover",
"snow depth (cm)",
"state of ground",
"additional information",
"liquid precipitation amount Sec 2(mm)",
"precipitation duration Sec 2 (hr)",
"24 hr precipitation (mm)",
"cloud coverage of layer",
"genus of cloud",
"height of cloud base",
"Special Phenomena Group",
"visibility (km)"
};

#endif
